### PR TITLE
feat: updated to use jxt cli get subdomain command

### PR DESCRIPTION
**Pull request by cagiti**

### CODE REVIEW

**Comment by garethjevans** [comment]
@cagiti I kicked this off again cause there was an issue with the template - hopefully temporary

**Comment by cagiti** [comment]
@garethjevans : nah it's the rebase I performed, seems that there are 2 get token step calls, I'll remove one... but will also have to then move the `jxt get subdomain` step, fingers crossed

**Comment by cagiti** [comment]
let's see how the latest commit goes

**Comment by garethjevans** [comment]
```{"level":"info","msg":"No domain flag provided so using default 34.73.168.172.nip.io to generate Ingress rules","time":"2019-11-18T11:00:37Z"}
{"level":"info","msg":"defaulting the domain to 34.73.168.172.nip.io and modified /home/jenkins/arcalos-boot-config/jx-requirements.yml\n","time":"2019-11-18T11:00:37Z"}
error: TLS is not supported with automated domains like 34.73.168.172.nip.io, you will need to use a real domain you own
error: failed to interpret pipeline file /home/jenkins/arcalos-boot-config/jenkins-x.yml: failed to run '/bin/sh -c jx step create install values -b --lazy-create=true --verbose' command in directory '/home/jenkins/arcalos-boot-config/env', output: ''```

**Comment by garethjevans** [comment]
I think this can be closed in favour of #121

**Pull request closed without merging**
